/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Kai Tong Teoh
 */
public class ScreenShotWindow extends javax.swing.JFrame {

    /**
     * Creates new form ScreenShotWindow
     */
    public ScreenShotWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane2 = new javax.swing.JEditorPane();
        jLabel8 = new javax.swing.JLabel();

        setTitle("Screen Shot Window");
        setPreferredSize(new java.awt.Dimension(800, 640));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Choose location to save files");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 180, 16);

        jLabel2.setText("Save images to:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 30, 100, 16);

        jScrollPane1.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 20, 290, 30);

        jButton1.setText("Choose...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(400, 20, 90, 28);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 70, 800, 10);

        jLabel3.setText("Capture Entire window or screen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 80, 190, 16);

        jButton2.setText("Resize Small");
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 170, 101, 28);

        jButton3.setText("Resize Large");
        getContentPane().add(jButton3);
        jButton3.setBounds(130, 170, 101, 28);

        jButton4.setText("Blue Background");
        getContentPane().add(jButton4);
        jButton4.setBounds(240, 170, 122, 28);

        jButton5.setText("White Background");
        getContentPane().add(jButton5);
        jButton5.setBounds(370, 170, 128, 28);

        jLabel4.setText("Background and Size");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 150, 120, 16);

        jButton6.setText("Capture Window Only");
        getContentPane().add(jButton6);
        jButton6.setBounds(30, 110, 150, 28);

        jButton7.setText("Capture Full Window");
        getContentPane().add(jButton7);
        jButton7.setBounds(190, 110, 150, 28);

        jButton8.setText("Capture Screen Only");
        getContentPane().add(jButton8);
        jButton8.setBounds(350, 110, 150, 28);

        jButton9.setText("Capture Full Screen");
        getContentPane().add(jButton9);
        jButton9.setBounds(510, 110, 140, 28);

        jCheckBox1.setText("Wait 5 seconds and capture frontmost window/dialog");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(140, 210, 320, 18);

        jLabel5.setText("Capture part of a project window");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 250, 180, 16);

        jButton10.setText("All Toolbars");
        getContentPane().add(jButton10);
        jButton10.setBounds(20, 270, 93, 28);

        jButton11.setText("Selection Bar");
        getContentPane().add(jButton11);
        jButton11.setBounds(120, 270, 110, 28);

        jButton12.setText("Tools");
        getContentPane().add(jButton12);
        jButton12.setBounds(240, 270, 59, 28);

        jButton13.setText("Transport");
        getContentPane().add(jButton13);
        jButton13.setBounds(310, 270, 90, 28);

        jButton14.setText("Mixer");
        getContentPane().add(jButton14);
        jButton14.setBounds(410, 270, 56, 28);

        jButton15.setText("Edit");
        getContentPane().add(jButton15);
        jButton15.setBounds(500, 270, 49, 28);

        jButton16.setText("Meter");
        getContentPane().add(jButton16);
        jButton16.setBounds(590, 270, 58, 28);

        jButton17.setText("Ruler");
        getContentPane().add(jButton17);
        jButton17.setBounds(680, 270, 58, 28);

        jLabel6.setText("Scale");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 330, 31, 16);

        jButton18.setText("One Sec");
        getContentPane().add(jButton18);
        jButton18.setBounds(20, 350, 75, 28);

        jButton19.setText("Ten Sec");
        getContentPane().add(jButton19);
        jButton19.setBounds(110, 350, 73, 28);

        jButton20.setText("One Min");
        getContentPane().add(jButton20);
        jButton20.setBounds(200, 350, 73, 28);

        jButton21.setText("Five Min");
        getContentPane().add(jButton21);
        jButton21.setBounds(290, 350, 72, 28);

        jLabel7.setText("Or Custom Scale Time");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 390, 130, 16);

        jScrollPane2.setViewportView(jEditorPane2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 410, 118, 30);

        jLabel8.setText("Value:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 420, 41, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //NewWindow newWindow = new NewWindow();
        //newWindow.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScreenShotWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScreenShotWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScreenShotWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScreenShotWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScreenShotWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JEditorPane jEditorPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
